"""
24/01/2024
Ayman Dghoughi, Nizar El Khoulfi, Ian Díaz
ASIXcB e3 UF1
Programa de traducció d’insults. Crear una estructura de dues dimensions amb els insults en català i afegir la traducció en castellà, anglès i klingon
El programa, demanarà a l’usuari que escrigui per teclat un insult, en català, i el mostrarà traduït a castellà, anglès i klingon.
"""

insults = {'CAT': ('CARALLOT', 'MOCÓS', 'MALPARIT', 'TROS DE QUÒNIAM', 'FLASCA', 'TARAL·LIROT', 'LLONDRO', 'ABRAÇAFANALS', 'AFAITAPAGESOS', 'BORDEGÀS', 'PELACANYES', 'BOTIFLER', 'ESTAQUIROT', 'BALIGA-BALAGA', 'BAGASSA', 'BRÈTOL', 'GALIFARDEU', 'LLEPACULS', 'BENEIT', 'PIXAPINS', 'BLEDA ASSOLELLADA', 'SÒMINES', 'ENZE', 'CAMACURT', 'CAPSIGRANY', 'CURT DE GAMBALS', 'FIGAFLOR', 'PASTANAGA', 'TANOCA', 'TÒTIL', 'LLANUT', 'GAMARÚS', 'PALLÚS', 'DROPO', 'PÒTOL', 'TALÓS', 'TRINXERAIRE', 'CAP DE SURO', 'POLLÓS', 'ABUSANANOS', 'BARBAMEC', 'PINXO', 'CUL D’OLLA', 'CAGABANDÚRRIES', 'CAGANER', 'MITJA MERDA', 'NAP-BUF', 'BORINOT', 'TITELLA', 'CAGADUBTES', 'POCA-TRAÇA', 'SAPASTRE', 'LLEPAFILS', 'POCA-SOLTA', 'NYÈBIT', 'CAP DE TRONS', 'BANYUT', 'CALÇASSES'),
           'ESP': ('CARALLO', 'MOCOS', 'MALPARIDO', 'TROZO DE CARNE', 'FLEMA', 'TARAL·LIROT', 'TONTOLABA', 'ARRASTRADO', 'ADULADOR', 'APROVECHADO', 'PERSONA POCO HONESTA', 'POBRE DIABLO', 'TRIPERO', 'PERSONA POCO SERIA', 'PROSTITUTA', 'SINVERGÜENZA', 'TRAIDOR', 'LAMEBOTAS', 'INGENUO', 'TERCO', 'INSIGNIFICANTE', 'ENCANTADO', 'INÚTIL', 'CORTO DE PIERNAS', 'CABEZA DE TERMO', 'CORTO DE ENTENDIMIENTO', 'FLOJO', 'PASOTA', 'TORPE', 'IGNORANTE', 'GROSERO', 'ATRASADO', 'QUE HUYE DEL TRABAJO', 'VAGO', 'CORTO DE INTELIGENCIA', 'INDECISO', 'DESPRECIABLE', 'INCAPAZ', 'MANGA ANCHA', 'PESADO', 'MANIPULABLE', 'INDECISO', 'TORPE', 'DESPRECIABLE', 'OBNUBILADO', 'INCAPAZ', 'ALUCINADO', 'IDIOTA', 'PUSILÁNIME', 'COBARDE', 'MEDIOCRE', 'PESADO', 'TÍTERE', 'INSEGURO', 'POCO HÁBIL', 'TORPE', 'INCAPAZ', 'LAMIENDO BOTAS', 'MUY MANIÁTICO CON LA COMIDA', 'PESADO', 'CARENTE DE DISTINCIÓN', 'CABEZA DE TRUENO', 'LOCO', 'QUE LE HAN PUESTO LOS CUERNOS', 'MANIPULABLE POR SU PAREJA'),
           'ENG': ('JERK', 'SNOT', 'SCOUNDREL', 'BLOCKHEAD', 'PHLEGM', 'FOOL', 'DUNDERHEAD', 'GROVELER', 'SUCK-UP', 'EXPLOITER', 'RASCAL', 'POOR DEVIL', 'TURNCOAT', 'FRIVOLOUS PERSON', 'PROSTITUTE', 'SCOUNDREL', 'TRAITOR', 'SUCK-UP', 'INGENUOUS PERSON', 'STUBBORN', 'INSIGNIFICANT', 'DELIGHTED', 'USELESS', 'SHORT-LEGGED', 'THICKHEADED', 'DIMWITTED', 'SLACKER', 'CARELESS', 'CLUMSY', 'IGNORANT', 'RUDE', 'BACKWARD', 'WORK-SHY', 'LAZY', 'DIMWITTED', 'INDECISIVE', 'DESPICABLE', 'INCAPABLE', 'WIDE-OPEN', 'TEDIOUS', 'MANIPULABLE', 'INDECISIVE', 'CLUMSY', 'DESPICABLE', 'OBTUSE', 'INCAPABLE', 'ASTOUNDED', 'IDIOTIC', 'TIMID', 'COWARDLY', 'MEDIOCRE', 'TEDIOUS', 'PUPPET', 'INSECURE', 'UNSKILLED', 'CLUMSY', 'INCAPABLE', 'BOOTLICKER', 'OVERLY PICKY WITH FOOD', 'TEDIOUS', 'LACKING DISTINCTION', 'HEAD OF THUNDER', 'CRAZY', 'HORNED', 'MANIPULABLE BY HIS/HER PARTNER'),
           'KLI': ('kJERK', 'kSNOT', 'kSCOUNDREL', 'kBLOCKHEAD', 'kPHLEGM', 'kFOOL', 'kDUNDERHEAD', 'kGROVELER', 'kSUCK-UP', 'kEXPLOITER', 'kRASCAL', 'kPOOR DEVIL', 'kTURNCOAT', 'kFRIVOLOUS PERSON', 'kPROSTITUTE', 'kSCOUNDREL', 'kTRAITOR', 'kSUCK-UP', 'kINGENUOUS PERSON', 'kSTUBBORN', 'kINSIGNIFICANT', 'kDELIGHTED', 'kUSELESS', 'kSHORT-LEGGED', 'kTHICKHEADED', 'kDIMWITTED', 'kSLACKER', 'kCARELESS', 'kCLUMSY', 'kIGNORANT', 'kRUDE', 'kBACKWARD', 'kWORK-SHY', 'kLAZY', 'kDIMWITTED', 'kINDECISIVE', 'kDESPICABLE', 'kINCAPABLE', 'kWIDE-OPEN', 'kTEDIOUS', 'kMANIPULABLE', 'kINDECISIVE', 'kCLUMSY', 'kDESPICABLE', 'kOBTUSE', 'kINCAPABLE', 'kASTOUNDED', 'kIDIOTIC', 'kTIMID', 'kCOWARDLY', 'kMEDIOCRE', 'kTEDIOUS', 'kPUPPET', 'kINSECURE', 'kUNSKILLED', 'kCLUMSY', 'kINCAPABLE', 'kBOOTLICKER', 'kOVERLY', 'kPICKY', 'kWITH', 'kFOOD', 'kTEDIOUS', 'kLACKING', 'kDISTINCTION', 'kHEAD', 'kOF', 'kTHUNDER', 'kCRAZY', 'kHORNED', 'kMANIPULABLE', 'kBY', 'kHIS/HER', 'kPARTNER')}
try:
    insult = input().upper()
    for i in range(len(insults["CAT"])):
        if insults['CAT'][i] == insult:
            print(f'Espanyol:\t{insults["ESP"][i]}\nAnglès:\t\t{insults["ENG"][i]}\nKlingon:\t{insults["KLI"][i]}')
    if insult not in insults:
        raise Exception("El insulto no existe en la base de datos de birus actualizada")
except Exception as e:
    print(e)
    exit(1)
